fileVersion: 1
id: 323a3cf7-51bd-402a-a378-cb4b38060fc0
name: TEST_SOURCE_VALUES
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
    truncateBefore: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: a383d13d-8100-4313-9012-024a53388ba9
          stepCounter: 323a3cf7-51bd-402a-a378-cb4b38060fc0
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        keyColumnType: None
        name: empid
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
        systemColumnType: None
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 027a3616-fbc7-4eb8-83b1-327353310514
          stepCounter: 323a3cf7-51bd-402a-a378-cb4b38060fc0
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        keyColumnType: None
        name: amount
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
        systemColumnType: None
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 7f003431-2736-43c0-b6ce-14104ba0f091
          stepCounter: 323a3cf7-51bd-402a-a378-cb4b38060fc0
        config: {}
        dataType: VARCHAR
        defaultValue: ""
        description: ""
        keyColumnType: None
        name: quarter
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
        systemColumnType: None
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases: {}
        customSQL:
          customSQL: ""
        dependencies: []
        join:
          joinCondition: ""
        name: TEST_SOURCE_VALUES
        noLinkRefs: []
  name: TEST_SOURCE_VALUES
  overrideSQL: false
  schema: ""
  sqlType: Stage
  type: sql
  version: 1
type: Node
